services:
    api:
        env_file:
            - ../.env
        build:
            context: ..
            dockerfile: docker/api/Dockerfile
        volumes:
            - ../:/var/www/html:cached
            - vendordata:/var/www/html/vendor
        command: php artisan serve --host=0.0.0.0 --port=8000
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - laravel

    web:
        build:
            context: ..
            dockerfile: docker/web/Dockerfile
        container_name: new-web
        volumes:
            - ../resources/frontend:/app:cached
            - web_node_modules:/app/node_modules
        ports:
            - "5173:5173"
        depends_on:
            - api
        networks:
            - laravel

    db:
        image: postgres:16-alpine
        container_name: new-db
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

volumes:
    db_data:
    vendordata:
    web_node_modules:
networks:
    laravel:
        driver: bridge
